# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7818e6baaeca53dee5695d46c083b895c91e6a5105cc51fb051cf01e5a8d075e72156c2ad3c398eaa7e53d5d769972386fdcaedc763d7a7823cd7271edf43c14

test:
  secret_key_base: f6d5d0d7f81664941b7ff6dddaab9ef3dbbd83c64590e8e1dbf809a8ba0aaa3bd227af6fd371bd528826f3fae47f9120aab956ed6edb7bc9e923061718d91506

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
